version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: myapp:latest
    container_name: app
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=r2dbc:postgresql://localhost:5432/mydb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
    depends_on:
      - charon_db
    restart: always


  charon_db:
    image: postgres:15
    container_name: postgres
    command: [ "postgres", "-c", "logging_collector=on", "-c", "log_statement=all" ]
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "127.0.0.1:5433:5432"

  redis:
    image: redis:7.0
    container_name: redis-container
    ports:
      - "6379:6379"